import { neon } from '@neondatabase/serverless';
import fs from 'fs';
const env = fs.readFileSync('.env.local','utf8');
const url = env.split('\n').find(l=>l.startsWith('DATABASE_URL=')).slice('DATABASE_URL='.length).trim();
const sql = neon(url);
const results = await sql`SELECT stage, slot, team_id, was_shootout FROM results WHERE stage IN ('r32','r16','qf','sf','final') ORDER BY stage, slot`;
console.log('=== knockout results ===');
for (const r of results) console.log(r.stage, r.slot, '->', r.team_id, 'shootout='+r.was_shootout);
const proc = await sql`SELECT fixture_id, processed_at FROM processed_fixtures WHERE fixture_id IN (537382,537428) ORDER BY fixture_id`;
console.log('=== processed 537382/537428 ===');
for (const r of proc) console.log(r.fixture_id, r.processed_at);
